# Generated by Django 4.0.6 on 2022-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mojeputovanje',
            name='slika',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
