# Generated by Django 4.0.6 on 2022-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mojeputovanje_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mojeputovanje',
            name='datum',
            field=models.DateField(null=True),
        ),
    ]
