# Generated by Django 4.0.6 on 2022-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mojeputovanje_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencija',
            name='datum_osnivanja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
