# Generated by Django 4.0.6 on 2022-09-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agencija_datum_osnivanja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mojeputovanje',
            name='user',
        ),
    ]
